# Generated by Django 5.0.6 on 2024-07-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='grandtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='shipping',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
    ]
